[[pages]]
path = "page/1_home.py"
name = "CDAC's AI-Powered Plant Disease Detection and Suggestion System"
icon = "ğŸŒ¿"  

[[pages]]
name = "Predict"
icon = "ğŸ”¬"  
is_section = true

[[pages]]
path = "page/2_prediction.py"
name = "Predict Disease Using CNN"
icon = "ğŸ§ " 

[[pages]]
path = "page/2_1.prediction_with_genai_suggestions.py"
name = "Predict Disease and Get Suggestions"
icon = "ğŸ’¡"

[[pages]]
name = "About"
icon = "â„¹ï¸" 
is_section = true

[[pages]]
path = "page/3_about.py"
name = "Our Team"
icon = "ğŸ“–"
